# GPS to ODOM Transform 
navsat_transform_node:
  ros__parameters:
    frequency: 30.0
    #delay: 3.0
    magnetic_declination_radians: 0.0 
    yaw_offset: 0.0 
    zero_altitude: true
    broadcast_utm_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: false
    wait_for_datum: false

# Complementary Filter
imu_complementary_filter:
  ros__parameters:

    # Magnetómetro
    use_mag: true

    # Ganancia
    gain_acc: 0.1
    gain_mag: 0.1

    do_bias_estimation: false
    do_adaptive_gain: true

    publish_tf: false
    remove_gravity_vector: false
    fixed_frame: odom

# EKF Filter Local
ekf_filter_node_odom:
    ros__parameters:
        frequency: 100.0
        sensor_timeout: 0.1
        two_d_mode: true
        publish_tf: true
 
        map_frame: map             
        odom_frame: odom            
        base_link_frame: base_link 
        world_frame: odom 

        #x     , y     , z,
        #roll  , pitch , yaw,
        #vx    , vy    , vz,
        #vroll , vpitch, vyaw,
        #ax    , ay    , az
        odom0: /ackermann_steering_controller/odometry
        odom0_config: [true, true, false,
                       false, false, true,
                       true, false, false,
                       false, false, true,
                       false, false, false]
        odom0_queue_size: 10
        odom0_relative: false
        odom0_differential: false

        imu0: /imu/data
        imu0_config: [false, false, false,
                      false, false, true,
                      false, false, false,
                      false, false, true,
                      true, false, false]
        imu0_queue_size: 10
        imu0_relative: true
        imu0_differential: false
        imu0_remove_gravitational_acceleration: true

# EKF Filter Global
ekf_filter_node_map:
    ros__parameters:
        frequency: 100.0
        sensor_timeout: 0.1
        two_d_mode: true
        publish_tf: true
 
        map_frame: map             
        odom_frame: odom            
        base_link_frame: base_link 
        world_frame: map 

        #x     , y     , z,
        #roll  , pitch , yaw,
        #vx    , vy    , vz,
        #vroll , vpitch, vyaw,
        #ax    , ay    , az
        odom0: /ackermann_steering_controller/odometry
        odom0_config: [true, true, false,
                       false, false, true,
                       true, false, false,
                       false, false, true,
                       false, false, false]
        odom0_queue_size: 10
        odom0_differential: false
        odom0_relative: false

        odom1: /odometry/gps
        odom1_config: [true,  true,  false,
                      false, false, false,
                      false, false, false,
                      false, false, false,
                      false, false, false]
        odom1_queue_size: 10
        odom1_differential: false
        odom1_relative: false

        imu0: /imu/data
        imu0_config: [false, false, false,
                      false, false, true,
                      false, false, false,
                      false, false, true,
                      true, false, false]
        imu0_relative: true
        imu0_differential: false
        imu0_remove_gravitational_acceleration: true
